### ISSUE TITLE
Hangs during opening

### ISSUE THREAD

**Issue by tischi** [mobie/covid-if-project#1] opened 2022-04-14 13:50 UTC
@constantinpape 
For me it hangs during opening.
Last line in log window: 
```
Opening table:
https://raw.githubusercontent.com/mobie/covid-if-project/main/data/20200406_164555_328/tables/sites/default.tsv
```
Same for you?

**Comment by constantinpape** [comment] 2022-04-14 13:54
No, it doesn't hang for me, just takes very long.

**Comment by tischi** [comment] 2022-04-14 13:55
But the default view should only load two wells, that should be fast, shouldn't it?

**Comment by constantinpape** [comment] 2022-04-14 13:59
I think it still has to load the whole tables for all wells / images and then just selects the subset shown in the view.
We only have two tables `wells` / `tables` here to avoid duplication of this data.

**Comment by tischi** [comment] 2022-04-14 14:05
This is really weird, because I was using the default view all the time (today and yesterday) for testing the boundary stuff and it would load within about 1 minute. Now it is really stuck for me (many minutes....). You did not change anything on the default view, did you?

**Comment by constantinpape** [comment] 2022-04-14 14:06
> This is really weird, because I was using the default view all the time (today and yesterday) for testing the boundary stuff and it would load within about 1 minute. Now it is really stuck for me (many minutes....). You did not change anything on the default view, did you?

No, I didn't change anything; but either your local internet or the EMBL S3 might have a lower bandwidth today. (Or did you maybe even try at EMBL and are at home now?)

**Comment by tischi** [comment] 2022-04-14 14:13
I am at EMBL, not sure what's going on. Anyway, for now most important that it works for you.
I leave the issue open until it works also for me again..

**Comment by constantinpape** [comment] 2022-04-14 14:16
> I am at EMBL, not sure what's going on. Anyway, for now most important that it works for you.
> I leave the issue open until it works also for me again..

Yeah, I will open it from local filesystem anyways to make the figure. But we'll need to improve the loading via s3 a bit once we publish the paper / put out the preprint...

**Comment by constantinpape** [comment] 2022-04-19 09:08
Hey @tischi,
I can reproduce this now. Turns out I hadn't updated to the latest MoBIE-beta version before. Now that I have loading the table hangs for me too, both when loading the project locally and from s3.

**Comment by constantinpape** [comment] 2022-04-24 21:04
This is fixed now.

**Closed as completed by constantinpape** 2022-04-24 21:04 UTC
Labels: bug
